name: Release Retina Container Images

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: read
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio when running outside of PRs.
  id-token: write

jobs:
  retina-images:
    name: Build Agent Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ["linux"]
        arch: ["amd64", "arm64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build/Push Images
        shell: bash
        run: |
          set -euo pipefail
          echo "TAG=$(make version)" >> $GITHUB_ENV
          make retina-image \
            IMAGE_NAMESPACE=${{ github.repository }} \
            PLATFORM=${{ matrix.platform }}/${{ matrix.arch }} \
            BUILDX_ACTION=--push

      - name: Sign container image
        run: |
          for image in \
            ghcr.io/${{ github.repository }}/retina-agent:$TAG-${{ matrix.platform }}-${{ matrix.arch }} \
            ghcr.io/${{ github.repository }}/retina-init:$TAG-${{ matrix.platform }}-${{ matrix.arch }} \
          ; do
            docker pull ${image}
            DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${image})
            cosign sign --yes ${DIGEST} 
          done

  retina-win-images:
    name: Build Agent Windows Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ["windows"]
        arch: ["amd64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build/Push Images
        shell: bash
        run: |
          set -euo pipefail
          echo "TAG=$(make version)" >> $GITHUB_ENV
          make retina-image-win \
            IMAGE_NAMESPACE=${{ github.repository }} \
            PLATFORM=${{ matrix.platform }}/${{ matrix.arch }} \
            BUILDX_ACTION=--push

      - name: Sign container image
        run: |
          for image in \
            ghcr.io/${{ github.repository }}/retina-agent:$TAG-windows-ltsc2019-${{ matrix.arch }} \
            ghcr.io/${{ github.repository }}/retina-init:$TAG-windows-ltsc2019-${{ matrix.arch }} \
            ghcr.io/${{ github.repository }}/retina-agent:$TAG-windows-ltsc2022-${{ matrix.arch }} \
            ghcr.io/${{ github.repository }}/retina-init:$TAG-windows-ltsc2022-${{ matrix.arch }} \
          ; do
            docker pull ${image}
            DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${image})
            cosign sign --yes ${DIGEST}
          done

  operator-images:
    name: Build Operator Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ["linux"]
        arch: ["amd64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build/Push Images
        shell: bash
        run: |
          set -euo pipefail
          echo "TAG=$(make version)" >> $GITHUB_ENV
          make retina-operator-image \
            IMAGE_NAMESPACE=${{ github.repository }} \
            PLATFORM=${{ matrix.platform }}/${{ matrix.arch }} \
            BUILDX_ACTION=--push

      - name: Sign container image
        run: |
          for image in \
            ghcr.io/${{ github.repository }}/retina-operator:$TAG \
            ghcr.io/${{ github.repository }}/retina-operator:$TAG-${{ matrix.platform }}-${{ matrix.arch }} \
          ; do
            docker pull ${image}
            DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${image})
            cosign sign --yes ${DIGEST}
          done

  manifests:
    name: Generate Manifests
    runs-on: ubuntu-latest
    needs: [retina-images, retina-win-images, operator-images]

    strategy:
      matrix:
        component: ["retina", "operator"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Generate Manifests
        shell: bash
        run: |
          set -euo pipefail
          make manifest \
            IMAGE_NAMESPACE=${{ github.repository }} \
            COMPONENT=${{ matrix.component }}

      - name: Sign manifests
        run: |
          for image in \
            ghcr.io/${{ github.repository }}/retina-agent:$TAG \
            ghcr.io/${{ github.repository }}/retina-init:$TAG \
            ghcr.io/${{ github.repository }}/retina-operator:$TAG \
          ; do
            docker pull ${image}
            DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${image})
            cosign sign --yes ${DIGEST} 
          done
